# Declaring the user list
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ericaskari-dev-auth
  namespace: ericaskari-dev
spec:
  basicAuth:
    secret: ericaskari-dev-auth-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: ericaskari-dev-auth-secret
  namespace: ericaskari-dev
data:
  users: |2
    myPass
