apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-ericaskari-meet-frontend
spec:
    replicas: 3
    selector:
        matchLabels:
            app.kubernetes.io/name: deployment-ericaskari-meet-frontend
    template:
        metadata:
            labels:
                app.kubernetes.io/name: deployment-ericaskari-meet-frontend
        spec:
            containers:
                - image: 438380764554.dkr.ecr.eu-west-1.amazonaws.com/ericaskari-meet-frontend:1.43.3-0
                  name: container-ericaskari-meet-frontend
                  imagePullPolicy: IfNotPresent
            imagePullSecrets:
                - name: regcred
