inputs:
  name:
    description: 'Your name'
    required: false
    default: 'No name provided'
name: CONFIGURE_AWS_CLI
description: CONFIGURE_AWS_CLI
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
