inputs:
  name:
    description: 'Your name'
    required: false
    default: 'No name provided'
name: CONFIGURE_AWS_CLI
description: CONFIGURE_AWS_CLI
runs:
  using: "composite"
  steps:
    - run: |
        echo STEP: SCRIPT_CONFIGURE_AWS_CLI
        unzip -q _ci/.aws/awscliv2.zip
        ./aws/install
        rm -rf .aws
        mkdir $HOME/.aws
        cp ./_ci/.aws/config $HOME/.aws/config
        cp ./_ci/.aws/credentials $HOME/.aws/credentials
        sed -i='' -e "s|<AWS_ACCESS_KEY_ID>|${AWS_ACCESS_KEY_ID}|" $HOME/.aws/credentials
        sed -i='' -e "s|<AWS_SECRET_ACCESS_KEY>|${AWS_SECRET_ACCESS_KEY}|" $HOME/.aws/credentials
      shell: bash
