apiVersion: v1
kind: Secret
metadata:
  name: secret-ericaskari-backend
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm

# yq e -i '.data.USER_NAME= "HELLOW"' ./_ci/deployment/backend-01-secret.yml
