apiVersion: v1
kind: Service
metadata:
  name: service-ericaskari-frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: deployment-ericaskari-frontend
  sessionAffinity: None
  type: ClusterIP
