name: Docker Image Build
on:
    push:
        branches: [main, production]
jobs:
    GenerateVersion:
        runs-on: self-hosted
        steps:
            - name: Pull Source Code
              uses: actions/checkout@v3
            - name: Configure Aws CLI
              uses: ./.github/workflows/configure-awscli
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            - name: Configure Nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Make executable
              run: chmod +x ./.github/scripts/STEP_GENERATE_VERSION.sh
              shell: bash
            - name: Execute
              run: ./.github/scripts/STEP_GENERATE_VERSION.sh
              id: versions
              shell: bash
            - name: Debug
              shell: bash
              run: |
                echo "OLD_PROD_RELEASE  ${{ steps.versions.outputs.OLD_PROD_RELEASE }}"
                echo "NEW_PROD_RELEASE  ${{ steps.versions.outputs.NEW_PROD_RELEASE }}"
                echo "OLD_DEV_RELEASE   ${{ steps.versions.outputs.OLD_DEV_RELEASE }}"
                echo "NEW_DEV_RELEASE   ${{ steps.versions.outputs.NEW_DEV_RELEASE }}"
        outputs:
          OLD_PROD_RELEASE: ${{ steps.versions.outputs.OLD_PROD_RELEASE }}
          NEW_PROD_RELEASE: ${{ steps.versions.outputs.NEW_PROD_RELEASE }}
          OLD_DEV_RELEASE: ${{ steps.versions.outputs.OLD_DEV_RELEASE }}
          NEW_DEV_RELEASE: ${{ steps.versions.outputs.NEW_DEV_RELEASE }}
    GetLatestTag:
        runs-on: self-hosted
        steps:
            - name: Get Latest Tag
              uses: WyriHaximus/github-action-get-previous-tag@v1
              with:
                fallback: 1.0.0

    BuildAndTest:
        runs-on: self-hosted
        if: github.ref_name != 'production'
        steps:
            - name: Pull Source Code
              uses: actions/checkout@v3
            - name: Configure Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Test
              shell: bash
              run: npm run test:all
            - name: Build
              shell: bash
              run: npm run build:all
            - name: Upload dist
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist
    BuildAndPushDockerImages:
        needs: [GenerateVersion, BuildAndTest]
        if: github.ref_name == 'main'
        runs-on: ubuntu-latest
        steps:
            - name: Pull Source Code
              uses: actions/checkout@v3
            - name: Configure Aws CLI
              uses: ./.github/workflows/configure-awscli
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            - name: Download dist
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist
            - name: Login
              shell: bash
              run: docker login -u AWS -p $(aws ecr get-login-password --region eu-west-1) 438380764554.dkr.ecr.eu-west-1.amazonaws.com
            - name: Build And Push
              shell: bash
              run: |
                  BE_TAG="438380764554.dkr.ecr.eu-west-1.amazonaws.com/ericaskari-backend:${{needs.GenerateVersion.outputs.NEW_DEV_RELEASE}}"
                  FE_TAG="438380764554.dkr.ecr.eu-west-1.amazonaws.com/ericaskari-frontend:${{needs.GenerateVersion.outputs.NEW_DEV_RELEASE}}"
                  echo BE_TAG: $BE_TAG
                  echo FE_TAG: $FE_TAG
                  docker build -f ./.github/Backend.Dockerfile --build-arg APP_BUILD_VERSION="${{needs.GenerateVersion.outputs.NEW_DEV_RELEASE}}" --tag "$BE_TAG" .
                  docker build -f ./.github/Frontend.Dockerfile --build-arg APP_BUILD_VERSION="${{needs.GenerateVersion.outputs.NEW_DEV_RELEASE}}" --tag "$FE_TAG" .
                  docker push "$BE_TAG"
                  docker push "$FE_TAG"
    PullAndUpdateImageTag:
        needs: [GenerateVersion]
        if: github.ref_name == 'production'
        runs-on: ubuntu-latest
        steps:
            - name: Pull Source Code
              uses: actions/checkout@v3
            - name: Configure Aws CLI
              uses: ./.github/workflows/configure-awscli
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            - name: Login
              shell: bash
              run: docker login -u AWS -p $(aws ecr get-login-password --region eu-west-1) 438380764554.dkr.ecr.eu-west-1.amazonaws.com
            - name: Build And Push
              shell: bash
              run: |
                  BackendImage="438380764554.dkr.ecr.eu-west-1.amazonaws.com/ericaskari-backend:${{needs.GenerateVersion.outputs.OLD_DEV_RELEASE}}"
                  NewBackendImage="438380764554.dkr.ecr.eu-west-1.amazonaws.com/ericaskari-backend:${{needs.GenerateVersion.outputs.NEW_PROD_RELEASE}}"

                  FrontendImage="438380764554.dkr.ecr.eu-west-1.amazonaws.com/ericaskari-frontend:${{needs.GenerateVersion.outputs.OLD_DEV_RELEASE}}"
                  NewFrontendImage="438380764554.dkr.ecr.eu-west-1.amazonaws.com/ericaskari-frontend:${{needs.GenerateVersion.outputs.NEW_PROD_RELEASE}}"

                  echo BackendImage: $BackendImage
                  echo NewBackendImage: $NewBackendImage
                
                  echo FrontendImage: $FrontendImage
                  echo NewFrontendImage: $NewFrontendImage
                
                  docker pull $BackendImage
                  docker tag $BackendImage $NewBackendImage
                  docker push "$NewBackendImage"
                
                  docker pull $FrontendImage
                  docker tag $FrontendImage $NewFrontendImage
                  docker push "$NewFrontendImage"
                
    DeployToProd:
        runs-on: self-hosted
        needs: [GenerateVersion,PullAndUpdateImageTag]
        if: github.ref_name == 'production'
        environment: production
        steps:
            - name: Pull Source Code
              uses: actions/checkout@v3
            - name: Configure Aws CLI
              uses: ./.github/workflows/configure-awscli
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            - name: Configure Kubectl CLI
              uses: ./.github/workflows/configure-kubectl
              with:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
            - name: Configure yq CLI
              shell: bash
              run: sudo sh -c 'cp ./.github/tools/.yq/yq_linux_amd64-v4.17.2 /usr/bin/yq && chmod +x /usr/bin/yq'
            - name: Debug
              shell: bash
              run: |
                echo NEW_DEV_RELEASE ${{ needs.GenerateVersion.outputs.NEW_DEV_RELEASE }}
                aws --version
                kubectl version
                yq --version
            - name: Deploy
              uses: ./.github/workflows/deploy
              with:
                VERSION: ${{ needs.GenerateVersion.outputs.NEW_PROD_RELEASE }}
                APP_NAMESPACE: ericaskari-prod
                APP_NODE_ENV: production
                APP_HOST_NAME: www.ericaskari.com
                APP_ENABLE_SWAGGER: false
                APP_NODE_MAILER_HOST: smtppro.zoho.eu
                APP_NODE_MAILER_PORT: 465
                APP_NODE_MAILER_REJECT_UNAUTHORIZED: true
                APP_NODE_MAILER_AUTH_USER: ${{ secrets.APP_NODE_MAILER_AUTH_USER }}
                APP_NODE_MAILER_AUTH_PASS: ${{ secrets.APP_NODE_MAILER_AUTH_PASS }}
                APP_NODE_MAILER_SECURE: true
                APP_IS_SSL_ENABLED: true
                APP_GOOGLE_TAG_MANAGER_ID: GTM-MXC7C6F
                APP_FE_DOMAIN_ONE: ericaskari.com
                APP_FE_DOMAIN_TWO: www.ericaskari.com
    DeployToDev:
        runs-on: self-hosted
        needs: [GenerateVersion,BuildAndPushDockerImages]
        if: github.ref_name == 'main'
        environment: development
        steps:
          - name: Pull Source Code
            uses: actions/checkout@v3
          - name: Configure Aws CLI
            uses: ./.github/workflows/configure-awscli
            with:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: ${{ secrets.AWS_REGION }}
          - name: Configure Kubectl CLI
            uses: ./.github/workflows/configure-kubectl
            with:
              KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          - name: Configure yq CLI
            shell: bash
            run: sudo sh -c 'cp ./.github/tools/.yq/yq_linux_amd64-v4.17.2 /usr/bin/yq && chmod +x /usr/bin/yq'
          - name: Debug
            shell: bash
            run: |
              echo NEW_DEV_RELEASE ${{ needs.GenerateVersion.outputs.NEW_DEV_RELEASE }}
              aws --version
              kubectl version
              yq --version
          - name: Deploy
            uses: ./.github/workflows/deploy
            with:
                VERSION: ${{ needs.GenerateVersion.outputs.NEW_DEV_RELEASE }}
                APP_NAMESPACE: ericaskari-dev
                APP_NODE_ENV: development
                APP_HOST_NAME: test.ericaskari.com
                APP_ENABLE_SWAGGER: true
                APP_NODE_MAILER_HOST: smtppro.zoho.eu
                APP_NODE_MAILER_PORT: 465
                APP_NODE_MAILER_REJECT_UNAUTHORIZED: true
                APP_NODE_MAILER_AUTH_USER: ${{ secrets.APP_NODE_MAILER_AUTH_USER }}
                APP_NODE_MAILER_AUTH_PASS: ${{ secrets.APP_NODE_MAILER_AUTH_PASS }}
                APP_NODE_MAILER_SECURE: true
                APP_IS_SSL_ENABLED: true
                APP_GOOGLE_TAG_MANAGER_ID: GTM-W5235KZ
                APP_FE_DOMAIN_ONE: test.ericaskari.com
                APP_FE_DOMAIN_TWO: staging.ericaskari.com
